"""
Base Strategy Class - All strategies inherit from this.

This provides a common interface for all trading strategies,
making it easy to add new strategies without modifying core bot logic.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import List, Dict, Any, Optional
from datetime import datetime


class SignalType(Enum):
    """Type of trading signal"""
    BUY = "buy"
    SELL = "sell"
    CANCEL = "cancel"
    HOLD = "hold"


@dataclass
class Signal:
    """
    Trading signal generated by a strategy.
    
    Attributes:
        signal_type: BUY, SELL, CANCEL, or HOLD
        token_id: The Polymarket token ID to trade
        market_slug: Human-readable market identifier
        side: "YES" or "NO" outcome
        price: Limit price (0.01 to 0.99)
        size: Number of shares/contracts
        confidence: Strategy's confidence (0.0 to 1.0)
        reason: Human-readable explanation
        metadata: Additional strategy-specific data
    """
    signal_type: SignalType
    token_id: str
    market_slug: str
    side: str  # "YES" or "NO"
    price: float
    size: float
    confidence: float = 0.5
    reason: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.now)
    
    def __str__(self):
        return (
            f"{self.signal_type.value.upper()} {self.size:.2f} {self.side} "
            f"@ ${self.price:.3f} | {self.market_slug[:40]} | "
            f"confidence: {self.confidence:.0%}"
        )


@dataclass
class MarketData:
    """
    Market data passed to strategies for analysis.
    
    Attributes:
        token_id: Polymarket token ID
        condition_id: Market condition ID
        market_slug: Event slug for the market
        question: The market question
        outcome: YES or NO
        best_bid: Current best bid price
        best_ask: Current best ask price
        mid_price: (best_bid + best_ask) / 2
        spread: best_ask - best_bid
        volume_24h: 24-hour trading volume in USD
        liquidity: Order book depth
        last_price: Last traded price
        timestamp: When this data was captured
    """
    token_id: str
    condition_id: str
    market_slug: str
    question: str
    outcome: str
    best_bid: float
    best_ask: float
    mid_price: float
    spread: float
    volume_24h: float
    liquidity: float
    last_price: float
    timestamp: datetime = field(default_factory=datetime.now)
    orderbook: Optional[Dict] = None  # Full orderbook if available
    recent_trades: Optional[List[Dict]] = None  # Recent trades for VPIN
    end_date_ts: Optional[float] = None  # Unix sec when market resolves (for expiry checks)
    event_title: str = ""
    event_slug: str = ""
    has_real_quotes: bool = False
    accepting_orders: bool = True
    fees_enabled: bool = True
    fee_rate_bps: Optional[float] = None
    is_resolved: bool = False
    resolution_outcome: Optional[str] = None
    data_source_quality: str = "unknown"
    quote_source: str = "gamma"
    tick_size: Optional[float] = None  # CLOB min tick; for post-only bid placement

    @property
    def spread_cents(self) -> float:
        """Spread in cents"""
        return self.spread * 100
    
    @property
    def spread_pct(self) -> float:
        """Spread as percentage of mid price"""
        if self.mid_price == 0:
            return 0
        return (self.spread / self.mid_price) * 100


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    
    Subclasses must implement:
        - analyze(): Generate trading signals from market data
        - execute(): Execute trades based on signals
        
    Optional overrides:
        - on_order_filled(): Called when an order fills
        - on_order_cancelled(): Called when an order is cancelled
        - should_trade_market(): Filter which markets to trade
    """
    
    # Strategy metadata (override in subclasses)
    name: str = "base"
    description: str = "Base strategy - do not use directly"
    version: str = "1.0.0"
    
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        """
        Initialize strategy with optional configuration.
        
        Args:
            config: Strategy-specific configuration dict
        """
        self.config = config or {}
        self.is_running = False
        self.signals_generated = 0
        self.trades_executed = 0
        self.pnl = 0.0
        self._last_scan_status = "idle"
        
    @abstractmethod
    def analyze(self, market_data: List[MarketData]) -> List[Signal]:
        """
        Analyze market data and generate trading signals.
        
        This is the core strategy logic. Implement your edge here.
        
        Args:
            market_data: List of MarketData objects for available markets
            
        Returns:
            List of Signal objects (can be empty if no opportunities)
        """
        pass
    
    @abstractmethod
    def execute(self, signals: List[Signal], order_manager) -> List[Dict]:
        """
        Execute trades based on generated signals.
        
        Args:
            signals: List of Signal objects from analyze()
            order_manager: OrderManager instance for placing orders
            
        Returns:
            List of order results/receipts
        """
        pass
    
    def should_trade_market(self, market_data: MarketData) -> bool:
        """
        Filter which markets this strategy should trade.
        
        Override to implement market selection logic.
        Default: trade all markets.
        
        Args:
            market_data: Market to evaluate
            
        Returns:
            True if strategy should consider this market
        """
        return True
    
    def on_order_filled(self, order_id: str, fill_data: Dict):
        """
        Called when an order is filled.
        
        Override to implement fill handling logic.
        
        Args:
            order_id: ID of filled order
            fill_data: Fill details (price, size, etc.)
        """
        self.trades_executed += 1
    
    def on_order_cancelled(self, order_id: str, reason: str):
        """
        Called when an order is cancelled.
        
        Override to implement cancellation handling.
        
        Args:
            order_id: ID of cancelled order
            reason: Cancellation reason
        """
        pass
    
    def on_start(self):
        """Called when strategy starts running."""
        self.is_running = True
    
    def on_stop(self):
        """Called when strategy stops."""
        self.is_running = False
    
    def get_state(self) -> Dict[str, Any]:
        """
        Get current strategy state for monitoring/persistence.
        
        Returns:
            Dict with strategy state
        """
        return {
            "name": self.name,
            "version": self.version,
            "is_running": self.is_running,
            "signals_generated": self.signals_generated,
            "trades_executed": self.trades_executed,
            "pnl": self.pnl,
            "config": self.config
        }
    
    def __repr__(self):
        return f"<{self.__class__.__name__} name='{self.name}' running={self.is_running}>"


